language: java

before_install:
  - chmod +x gradlew

install:
  - ./gradlew dist

deploy:
  provider: releases
  api_key: ""
  file: "./desktop/build/libs/gameprot.jar"
  skip_cleanup: true
  on:
    tags: true